### ISSUE TITLE
Duplicate vignette titles

### ISSUE THREAD

**Issue by MashaAseeva** [CancerRxGene/gdscIC50#7]
When I run the command
devtools::install_github("cancerrxgene/gdscIC50", build_vignettes=TRUE)

I receive this error: 
`Downloading GitHub repo cancerrxgene/gdscIC50@master
✔  checking for file ‘/private/var/folders/3y/fb8r37bn0kbfkd2wg0rbyf10000snm/T/Rtmp0IoS54/remotes171b58d7160b/CancerRxGene-gdscIC50-d5a2a97/DESCRIPTION’ ...
─  preparing ‘gdscIC50’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (33.7s)
   duplicated vignette title:
     ‘Vignette Title’
   
   --- re-building ‘gdscIC50.Rmd’ using rmarkdown
   Different dilution series per DRUG_ID_lib are being treated
               separately to get maximum concentration and to set x values.
   Grouping all dilution series per DRUG_ID_lib to get maximum
               concentrations and to set x values.
   Different dilution series per DRUG_ID_lib are being treated
               separately to get maximum concentration and to set x values.
   --- finished re-building ‘gdscIC50.Rmd’
   
   --- re-building ‘gdsc_raw_data_format.Rmd’ using rmarkdown
   --- finished re-building ‘gdsc_raw_data_format.Rmd’
   
   Error: Duplicate vignette titles.
     Ensure that the %\VignetteIndexEntry lines in the vignette sources
     correspond to the vignette titles.
   Execution halted
Error: Failed to install 'gdscIC50' from GitHub:
  System command error, exit status: 1, stderr empty`

It appears that both the .rmd files in the vignettes have title 'Vignette Title'. R documentation states "You’ll need to modify the \VignetteIndexEntry to provide the title of your vignette as you’d like it to appear in the vignette index."

**Comment by DriessenA** [comment]
I have the same problem when trying to install GDSCIC50 on a MacBook, also running:

> devtools::install_github("cancerrxgene/gdscIC50", build_vignettes=TRUE)

I get exactly the same error as above

**Comment by howard-lightfoot** [comment]
I couldn't reproduce this error but I think I know what the problem was. I have hot-fixed both master and develop branches so it should now work. Please feel free to try again. Apologies for the tardy response.

Howard
